# Generated by Django 6.0.1 on 2026-01-31 17:09

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(default=utils.utils.generate_short_key, max_length=10),
        ),
    ]
